# Generated by Django 4.2.16 on 2024-11-19 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_about_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='update_on',
            new_name='updated_on',
        ),
    ]
